name: Deploy to pokedex.digitaldungeon.dev

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install and Build
      run: |
        npm ci
        npm run build

    - name: Deploy
      uses: Burnett01/rsync-deployments@5.2.1
      with:
        switches: -avz --delete
        path: dist/
        remote_path: /var/www/pokedex
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
