name: Update npm cache

on:
  push:
    branches:
      - master
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get .nvmrc
      run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      id: nvm

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.nvm.outputs.NVMRC }}

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        path: ~/.npm
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Packages
      # No need to install if hit, we are not building
      if: steps.cache-npm.outputs.cache-hit != 'true'
      run: npm ci